
development:
  adapter: postgresql
  encoding: unicode
  database: building_development
  pool: 5
  host: localhost
  username: Kit
  password:


test:
  adapter: postgresql 
  encoding: unicode
  database: building_test
  pool: 5
  host: localhost
  username: Kit
  password:


production:
  adapter: postgresql 
  encoding: unicode
  database: building_production
  pool: 5
  host: localhost
  username: Kit
  password:
